using HexaContent.Core;
using Microsoft.EntityFrameworkCore;

namespace HexaContent.Infrastructure.Extension;

internal static class DatabaseContextExtensions
{
	public static void AddAutogenerated<TEntity, TKey>(this ModelBuilder modelBuilder)
		where TEntity : EntityBase<TKey>
		where TKey : struct
	{
		modelBuilder.Entity<TEntity>().Property(f => f.Id).ValueGeneratedOnAdd();
	}
}
